codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  status:
    project: #checks for the overall code coverage rate of the repository
      default: 
        enabled: yes
        threshold: null
        target: auto
    patch:  #checks for the overall code coverage of the newly added code
      default:
        enabled: yes
        target: 80
