codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  status:
    project:
      default:
        target: auto  # Automatically set based on the base report (e.g., the default branch like main or master)
        threshold: 0%  # No tolerance for a decrease in coverage.
    patch:
      default:
        enabled: yes
        target: 80
        threshold: 20%
