name: PR Build

on: 
  pull_request:
    branches: [ "**" ]

jobs:
  call_workflow:
    name: Run PR Build Workflow
    if: ${{ github.repository_owner == 'your-organization' }}
    uses: asekawa/PR-Builder/.github/workflows/build-template.yml@main
    secrets: inherit
