name: Java CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  call_workflow:
    uses: asekawa/PR-Builder/.github/workflows/pr_builder.yml@main
    secrets: inherit
