name: PR Build

on: 
  pull_request:
    branches: [ "**" ]

jobs:
  call_workflow:
    name: Run PR Build Workflow
    uses: asekawa/Java-codecov-sample/.github/workflows/build-template.yml@main
    secrets: inherit
